services:
  web:
    build: .
    image: php:8.4-apache
    ports:
      - "8080:80"
      # If working with SSL, we can also route port 443.
      # 443:443
    volumes:
      - ../:/var/www/html
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL
    command: apache2-foreground

  mysql:
    # We don't have to point to a specific image here; instead, we could use: mysql:latest
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: studentpass
      MYSQL_DATABASE: dmit2025
      MYSQL_USER: student
      MYSQL_PASSWORD: student
      # We can also set it up so that the password field can be left blank or empty.
      # MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: studentpass
    depends_on:
      - mysql

volumes:
  mysql_data: